---

wordCathes:
  normal:
    regex: ".*(норма|norma).*"
    stickers:
      - "CAADAgADnQUAAlOx9wMjvcls38LyPwI"
  gopstop:
    regex: ".*(gop|гоп).*"
    stickers:
      - "CAADAgADXwMAAgw7AAEKTh8jAAH9Q-gAAQI"
