---

wordCathes:
  normal:
    regex: ".*(норма|norma).*"
    stickers:
      - "CAADAgADnQUAAlOx9wMjvcls38LyPwI"
  gopstop:
    regex: ".*(gop|гоп).*"
    stickers:
      - "CAADAgADXwMAAgw7AAEKTh8jAAH9Q-gAAQI"
      - "CAADAgADXwMAAgw7AAEKTh8jAAH9Q-gAAQI"
      - "CAADAgADXwMAAgw7AAEKTh8jAAH9Q-gAAQI"
      - "CAADAgADXwMAAgw7AAEKTh8jAAH9Q-gAAQI"
      - "CAADAgADXwMAAgw7AAEKTh8jAAH9Q-gAAQI"
      - "CAADAgADXwMAAgw7AAEKTh8jAAH9Q-gAAQI"
    gifs:
      - "CgADBAADDaAAAvwYZAcsF65UbbXDbgI"
    images:
      - "AgADAgADnqoxG22cUEn8gzuDaxEbmwvotw4ABP9cj0qxecfJtEsFAAEC"
